document.write(
		"<div class='flyout-menu' id='entertainment-menu' style='display:none;'>"
		+"<div style='width:200px;'>"
		+"<h3><a href='./all/entertainment/shopping/shopping_main.jsp'>Shopping</a></h3>"
		+"<h4><p>Shopping in Varanasi</p></h4>"
		+"<ul>"
			+"<li><a hrefhref='./all/entertainment/shopping/banarasi-saree.jsp'>Banarasi Saree</a></li>"
			+"<li><a href='./all/entertainment/shopping/carpets.jsp'>Banarasi Carpets</a></li>"
			+"<li><a href='./all/entertainment/shopping/handicrafts.jsp'>Handicrafts</a></li>"
		+"</ul>"
		
		+"</div>"
	+"</div>"
	+"<div class='flyout-menu' id='history-menu' style='display:none;'>"
		+"<div style='width:200px;'>"
		+"<h3><a href='./all/history/history_main.jsp'>History</a></h3>"
		+"<h4><p>Learn the rich history</p><h4>"

		+"<ul>"
			+"<li><a href='./all/history/history_banaras.jsp'>Banaras</a></li>"
			+"<li><a href='./all/history/history_sarnath.jsp'>Sarnath</a></li>"
			+"<li><a href='./all/history/history_ramnagar.jsp'>Ramnagar</a></li>"
			+"<li><a href='./all/history/ff.jsp'>Freedom Fighters</a></li>"
		+"</ul>"
		+"</div>"
	+"</div>"


	+"<div class='flyout-menu' id='tourism-menu' style='display:none;'>"
		+"<div style='width:200px;'>"
		
		+"<h3><a href='./all/tourism/visit.jsp'>Places to Visit</a></h3>"
		+"<h4><p>Important Places to visit</p></h4>"
		+"<ul>"
			+"<li><a href='./all/tourism/visit/visit_bkbhawan.jsp'>Bharat Kala Bhavan</a></li>"
			+"<li><a href='./all/tourism/visit/visit_jantar_mantar.jsp'>Jantar Mantar</a></li>"
			+"<li><a href='./all/education/education_bhu.jsp'>Banaras Hindu University</li>"
			+"<li><a href='./all/tourism/tourism_sarnath.jsp'>Sarnath</a></li>"
			+"<li><a href='./all/tourism/tourism_temple.jsp'>Temples in Varanasi</a></li>"
			+"<li><a href='./all/tourism/tourism_ghats.jsp'>Ghats of River Ganges</a></li>"
		+"</ul>"
		
		+"<h3><a href='./all/tourism/tourism_temple.jsp'>Temples</a></h3>"
		+"<h4><p>Temples in Varanasi</p></h4>"
		+"<ul>"
			+"<li><a href='./all/tourism/temples/bharatmata-mandir.jsp'>Bharat Mata Temple</a></li>"
			+"<li><a href='./all/tourism/temples/durga-temple.jsp'>Durga Temple</a></li>"
			+"<li><a href='./all/tourism/temples/new-vishwanath-temple.jsp'>New Vishwanath Temple</a></li>"
			+"<li><a href='./all/tourism/temples/sankat-mochan-temple.jsp'>Sankatmochan Temple</a></li>"
			+"<li><a href='./all/tourism/temples/tulsi-manas-mandir.jsp'>Tulsi Manas Temple</a></li>"
			+"<li><a href='./all/tourism/temples/vishwanath-temple.jsp'>Vishwanath Temple</a></li>"
		+"</ul>"	
		
		+"<h3><a href='./all/tourism/tourism_ghats.jsp'>Ghats</a></h3>"
		
		+"<ul>"
			+"<li><a href='./all/tourism/ghats/ghats1-20.jsp'>Ghats 1 to 20</a></li>"
			+"<li><a href='./all/tourism/ghats/ghats21-40.jsp'>Ghats 21 to 40</a></li>"
			+"<li><a href='./all/tourism/ghats/ghats41-60.jsp'>Ghats 41 to 60</a></li>"
			+"<li><a href='./all/tourism/ghats/ghat61-84.jsp'>Ghats 61 to 84</a></li>"
		+"</ul>"
		
		+"<h3><a href='./all/tourism/tourism_sarnath.jsp'>Sarnath</a></h3>"
		
		+"<ul>"
			+"<li><a href='./all/tourism/sarnath/archaeological-museum.jsp'>Sarnath Museum</a></li>"
			+"<li><a href='./all/tourism/sarnath/ashoka-pillar.jsp'>Ashoka Lion Capital</a></li>"
			+"<li><a href='./all/tourism/sarnath/buddhist-temples.jsp'>Buddhist Temples</a></li>"	
		+"</ul>"	
		+"<h4><p>Stupas at Sarnath</p></h4>"
		+"<ul>"
			+"<li><a href='./all/tourism/sarnath/chaukhandi-stupa.jsp'>Chaukhandi Stupa</a></li>"
			+"<li><a href='./all/tourism/sarnath/dhamek-stupa.jsp'>Dhamekha Stupa</a></li>"
			+"<li><a href='./all/tourism/sarnath/dharmrajika-stupa.jsp'>Dharmarajika Stupa</a></li>"
		+"</ul>"
		
		
		
		
		+"</div>"

	+"</div>"
	+"<div class='flyout-menu' id='education-menu' style='display:none;'>"
		+"<div style='width:200px;'>"
		+"<h3><a href='./all/education/education_main.jsp'>Education</a></h3>"
		+"<h4><p>Educational Institutes in Varanasi</p></h4>"
		+"<ul>"
			+"<li><a href='./all/education/education_bhu.jsp'>Banaras Hindu University</a></li>"
			+"<li><a href='./all/education/education_ssv.jsp'>Sampurnanand Sanskrit University</a></li>"
			+"<li><a href='./all/education/education_cihts.jsp'>Central Institute of Higher Tibetan Studies</a></li>"
			+"<li><a href='./education/education_other.jsp'>Other Institutes</a></li>"
		+"</ul>"
		+"</div>"
	+"</div>"
);

