document.write(
		"<div id='mainmenu'>"
		+"<ul>"
		+"<li><a id='home-link' href='./all/home.jsp'><span>Home</span></a></li>"
		+"<!-- li><a href='javascript:sendRequest('./all/history/history_main.jsp','bd');'><span>History</span></a></li-->"
		+"<li><a id='history-link' href='./all/history/history_main.jsp'><span>History</span></a></li>"
		+"<li><a id='personalities-link' href='./all/personalities/personalities_main.jsp'><span>Personalities</span></a></li>"
		+"<li><a id='education-link' href='./all/education/education_main.jsp'><span>Education</span></a></li>"
		+"<li><a id='entertainment-link' href='./all/entertainment/entertainment_main.jsp'><span>Entertainment</span></a><li>"
		+"<li><a id='tourism-link' href='./all/tourism/tourism_main.jsp'><span>Travel</span></a><li>"
		+"<li><a id='gallery-link' href='./all/gallery_main.jsp'><span>Gallery</span></a><li>"
		+"<li><a id='downloads-link' href='./all/downloads/downloads.jsp'><span>Downloads</span></a><li>"
		+"<li><a id='forum_main-link' href='./all/forum_main.jsp'><span>Forum</span></a><li>"
		+"<li><a id='news_main-link' href='./all/view_news.jsp'><span>View News</span></a><li>"
		+"<li><a id='news_main-link' href='./all/surf_map.jsp'><span>Surf Map</span></a><li>"
		+"<li><a id='news_main-link' href='./all/search_ads.jsp'><span>Search Ads</span></a><li>"
		+"<li><a id='sign_up_main-link' align='right' href='./sign_up_main.jsp'><span>Sign Up</span></a><li>"
		+"</ul>"
		+"</div>"
);