document.write(
		"<div id='mainmenu'>"
		+"<ul>"
		+"<li><a id='home-link' href='./home.jsp'><span>Home</span></a></li>"
		+"<!-- li><a href='javascript:sendRequest('./history/history_main.jsp','bd');'><span>History</span></a></li-->"
		+"<li><a id='history-link' href='./history/history_main.jsp'><span>History</span></a></li>"
		+"<li><a id='personalities-link' href='./personalities/personalities_main.jsp'><span>Personalities</span></a></li>"
		+"<li><a id='education-link' href='./education/education_main.jsp'><span>Education</span></a></li>"
		+"<li><a id='entertainment-link' href='./entertainment/entertainment_main.jsp'><span>Entertainment</span></a><li>"
		+"<li><a id='movies-link' href='./view_movies.jsp'><span>Movies</span></a><li>"
		+"<li><a id='tourism-link' href='./tourism/tourism_main.jsp'><span>Travel</span></a><li>"
		+"<li><a id='business-link' href='./business/business_main.jsp'><span>Business</span></a><li>"
		+"<li><a id='gallery-link' href='./gallery_main.jsp'><span>Gallery</span></a><li>"
		+"<li><a id='downloads-link' href='./downloads/downloads.jsp'><span>Downloads</span></a></li>"
		+"<li><a id='forum_main-link' href='./forum_main.jsp'><span>Forum</span></a><li>"
		+"<li><a id='view_news-link' href='./view_news.jsp'><span>View News</span></a><li>"
		+"<li><a id='surf_map-link' href='./surf_map.jsp'><span>Surf Map</span></a><li>"
		+"<li><a id='view_ads-link' href='./view_ads.jsp'><span>Search Ads</span></a><li>"
		
		+"<li><a id='update_profile-link' href='./update_profile.jsp'><span>Update Profile</span></a><li>"
		+"<li><a id='post_ads-link' align='right' href='./post_ads.jsp'><span>Post Free Ads</span></a><li>"
		+"<li><a id='rates-link' align='right' href='./view_rates.jsp'><span>View rates</span></a><li>"
		+"<li><a id='taxes-link' align='right' href='./view_taxes.jsp'><span>View taxes</span></a><li>"
		+"</ul>"
		+"</div>"
);